CATEGORIES = [
    {
        "Id": 10,
        "Sex": 1,
        "Description": "Muži",
        "ShortDescription": "M",
        "DescriptionEn": "Men",
        "ShortDescriptionEn": "M",
        "Age": "<100",
    },
    {
        "Id": 20,
        "Sex": 1,
        "Description": "Muži 20-22 let",
        "ShortDescription": "U23M",
        "DescriptionEn": "Men U23 ",
        "ShortDescriptionEn": "U23M",
        "Age": "<23",
    },
    {
        "Id": 30,
        "Sex": 1,
        "Description": "Junioři",
        "ShortDescription": "Jři",
        "DescriptionEn": "Men U20",
        "ShortDescriptionEn": "J",
        "Age": "<20",
    },
    {
        "Id": 40,
        "Sex": 1,
        "Description": "Dorostenci",
        "ShortDescription": "Dci",
        "DescriptionEn": "Boys U18",
        "ShortDescriptionEn": "U18M",
        "Age": "<18",
    },
    {
        "Id": 50,
        "Sex": 1,
        "Description": "Žáci",
        "ShortDescription": "Žci",
        "DescriptionEn": "Boys U16",
        "ShortDescriptionEn": "U16M",
        "Age": "<16",
    },
    {
        "Id": 60,
        "Sex": 1,
        "Description": "Ml. žáci",
        "ShortDescription": "Žcm",
        "DescriptionEn": "Boys U14",
        "ShortDescriptionEn": "U14M",
        "Age": "<14",
    },
    {
        "Id": 70,
        "Sex": 1,
        "Description": "Veteráni",
        "ShortDescription": "V",
        "DescriptionEn": "Masters  Men",
        "ShortDescriptionEn": "MM",
        "Age": ">35",
    },
    {
        "Id": 100,
        "Sex": 2,
        "Description": "Ženy",
        "ShortDescription": "Ž",
        "DescriptionEn": "Women",
        "ShortDescriptionEn": "W",
        "Age": "<100",
    },
    {
        "Id": 105,
        "Sex": 2,
        "Description": "Ženy 20-22 let",
        "ShortDescription": "U23Z",
        "DescriptionEn": "Women U23",
        "ShortDescriptionEn": "U23W",
        "Age": "<23",
    },
    {
        "Id": 110,
        "Sex": 2,
        "Description": "Juniorky",
        "ShortDescription": "Jky",
        "DescriptionEn": "Women U20",
        "ShortDescriptionEn": "U20W",
        "Age": "<20",
    },
    {
        "Id": 120,
        "Sex": 2,
        "Description": "Dorostenky",
        "ShortDescription": "Dky",
        "DescriptionEn": "Girls U18",
        "ShortDescriptionEn": "U18W",
        "Age": "<18",
    },
    {
        "Id": 130,
        "Sex": 2,
        "Description": "Žákyně",
        "ShortDescription": "Žky",
        "DescriptionEn": "Girls U16",
        "ShortDescriptionEn": "U16W",
        "Age": "<16",
    },
    {
        "Id": 140,
        "Sex": 2,
        "Description": "Ml. žákyně",
        "ShortDescription": "Žkm",
        "DescriptionEn": "Girls U14",
        "ShortDescriptionEn": "U14W",
        "Age": "<14",
    },
    {
        "Id": 150,
        "Sex": 2,
        "Description": "Veteránky",
        "ShortDescription": "Vky",
        "DescriptionEn": "Masters Women",
        "ShortDescriptionEn": "MW",
        "Age": ">35",
    },
    {
        "Id": 153,
        "Sex": 0,
        "Description": "Mix mladší žactvo",
        "ShortDescription": "Mix ml. žc",
        "DescriptionEn": "Mix ml. žactvo",
        "ShortDescriptionEn": "MIXYK",
        "Age": "<14",
    },
    {
        "Id": 154,
        "Sex": 0,
        "Description": "Mix starší žactvo",
        "ShortDescription": "Mix st. žc",
        "DescriptionEn": "Mix st. žactvo",
        "ShortDescriptionEn": "MIXK",
        "Age": "<16",
    },
    {
        "Id": 155,
        "Sex": 1,
        "Description": "Atletická minipřípravka-hoši",
        "ShortDescription": "EleHm",
        "DescriptionEn": "Mini Kids M",
        "ShortDescriptionEn": "MKM",
        "Age": "<10",
    },
    {
        "Id": 160,
        "Sex": 1,
        "Description": "Atletická přípravka-hoši",
        "ShortDescription": "EleH",
        "DescriptionEn": "Kids M",
        "ShortDescriptionEn": "KM",
        "Age": "<12",
    },
    {
        "Id": 165,
        "Sex": 2,
        "Description": "Atletická minipřípravka-dívky",
        "ShortDescription": "EleDm",
        "DescriptionEn": "Mini Kids W",
        "ShortDescriptionEn": "MKW",
        "Age": "<10",
    },
    {
        "Id": 170,
        "Sex": 2,
        "Description": "Atletická přípravka-dívky",
        "ShortDescription": "EleD",
        "DescriptionEn": "Kids W",
        "ShortDescriptionEn": "KW",
        "Age": "<12",
    },
    {
        "Id": 899,
        "Sex": 0,
        "Description": "Mix",
        "ShortDescription": "Mix",
        "DescriptionEn": "Mix",
        "ShortDescriptionEn": "Mix",
        "Age": "<100",
    },
    {
        "Id": 2007,
        "Sex": 1,
        "Description": "2007 Boys",
        "ShortDescription": "2007 B",
        "DescriptionEn": "2007 Boys",
        "ShortDescriptionEn": "2007 B",
        "Age": "==2007",
    },
    {
        "Id": 2008,
        "Sex": 1,
        "Description": "2008 Boys",
        "ShortDescription": "2008 B",
        "DescriptionEn": "2008 Boys",
        "ShortDescriptionEn": "2008 B",
        "Age": "==2008",
    },
    {
        "Id": 2009,
        "Sex": 1,
        "Description": "2009 Boys",
        "ShortDescription": "2009 B",
        "DescriptionEn": "2009 Boys",
        "ShortDescriptionEn": "2009 B",
        "Age": "==2009",
    },
    {
        "Id": 2010,
        "Sex": 1,
        "Description": "2010 Boys",
        "ShortDescription": "2010 B",
        "DescriptionEn": "2010 Boys",
        "ShortDescriptionEn": "2010 B",
        "Age": "==2010",
    },
    {
        "Id": 2011,
        "Sex": 1,
        "Description": "2011 Boys",
        "ShortDescription": "2011 B",
        "DescriptionEn": "2011 Boys",
        "ShortDescriptionEn": "2011 B",
        "Age": "==2011",
    },
    {
        "Id": 2012,
        "Sex": 1,
        "Description": "2012 Boys",
        "ShortDescription": "2012 B",
        "DescriptionEn": "2012 Boys",
        "ShortDescriptionEn": "2012 B",
        "Age": "==2012",
    },
    {
        "Id": 2013,
        "Sex": 1,
        "Description": "2013 Boys",
        "ShortDescription": "2013 B",
        "DescriptionEn": "2013 Boys",
        "ShortDescriptionEn": "2013 B",
        "Age": "==2013",
    },
    {
        "Id": 2014,
        "Sex": 1,
        "Description": "2014 Boys",
        "ShortDescription": "2014 B",
        "DescriptionEn": "2014 Boys",
        "ShortDescriptionEn": "2014 B",
        "Age": "==2014",
    },
    {
        "Id": 2015,
        "Sex": 1,
        "Description": "2015 Boys",
        "ShortDescription": "2015 B",
        "DescriptionEn": "2015 Boys",
        "ShortDescriptionEn": "2015 B",
        "Age": "==2015",
    },
    {
        "Id": 12007,
        "Sex": 2,
        "Description": "2007 Girls",
        "ShortDescription": "2007 G",
        "DescriptionEn": "2007 Girls",
        "ShortDescriptionEn": "2007 G",
        "Age": "==2007",
    },
    {
        "Id": 12008,
        "Sex": 2,
        "Description": "2008 Girls",
        "ShortDescription": "2008 G",
        "DescriptionEn": "2008 Girls",
        "ShortDescriptionEn": "2008 G",
        "Age": "==2008",
    },
    {
        "Id": 12009,
        "Sex": 2,
        "Description": "2009 Girls",
        "ShortDescription": "2009 G",
        "DescriptionEn": "2009 Girls",
        "ShortDescriptionEn": "2009 G",
        "Age": "==2009",
    },
    {
        "Id": 12010,
        "Sex": 2,
        "Description": "2010 Girls",
        "ShortDescription": "2010 G",
        "DescriptionEn": "2010 Girls",
        "ShortDescriptionEn": "2010 G",
        "Age": "==2010",
    },
    {
        "Id": 12011,
        "Sex": 2,
        "Description": "2011 Girls",
        "ShortDescription": "2011 G",
        "DescriptionEn": "2011 Girls",
        "ShortDescriptionEn": "2011 G",
        "Age": "==2011",
    },
    {
        "Id": 12012,
        "Sex": 2,
        "Description": "2012 Girls",
        "ShortDescription": "2012 G",
        "DescriptionEn": "2012 Girls",
        "ShortDescriptionEn": "2012 G",
        "Age": "==2012",
    },
    {
        "Id": 12013,
        "Sex": 2,
        "Description": "2013 Girls",
        "ShortDescription": "2013 G",
        "DescriptionEn": "2013 Girls",
        "ShortDescriptionEn": "2013 G",
        "Age": "==2013",
    },
    {
        "Id": 12014,
        "Sex": 2,
        "Description": "2014 Girls",
        "ShortDescription": "2014 G",
        "DescriptionEn": "2014 Girls",
        "ShortDescriptionEn": "2014 G",
        "Age": "==2014",
    },
    {
        "Id": 12015,
        "Sex": 2,
        "Description": "2015 Girls",
        "ShortDescription": "2015 G",
        "DescriptionEn": "2015 Girls",
        "ShortDescriptionEn": "2015 G",
        "Age": "==2015",
    },
]
