DISCIPLINES = [
    {
        "Id": 9,
        "Sort": 9,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 74,
        "LapsCount": 1,
        "Description": "100 yardů",
        "ShortDescription": "100 y",
        "DescriptionEn": "100 yards",
        "ShortDescriptionEn": "100 y",
    },
    {
        "Id": 10,
        "Sort": 10,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 50,
        "LapsCount": 1,
        "Description": "50 m",
        "ShortDescription": "50 m",
        "DescriptionEn": "50 Metres",
        "ShortDescriptionEn": "50 M",
    },
    {
        "Id": 20,
        "Sort": 20,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 60,
        "LapsCount": 1,
        "Description": "60 m",
        "ShortDescription": "60 m",
        "DescriptionEn": "60 Metres",
        "ShortDescriptionEn": "60 M",
    },
    {
        "Id": 30,
        "Sort": 30,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 80,
        "LapsCount": 1,
        "Description": "80 m",
        "ShortDescription": "80 m",
        "DescriptionEn": "80 Metres",
        "ShortDescriptionEn": "80 M",
    },
    {
        "Id": 40,
        "Sort": 40,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 100,
        "LapsCount": 1,
        "Description": "100 m",
        "ShortDescription": "100 m",
        "DescriptionEn": "100 Metres",
        "ShortDescriptionEn": "100 M",
    },
    {
        "Id": 50,
        "Sort": 50,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 150,
        "LapsCount": 1,
        "Description": "150 m",
        "ShortDescription": "150 m",
        "DescriptionEn": "150 Metres",
        "ShortDescriptionEn": "150 M",
    },
    {
        "Id": 60,
        "Sort": 60,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 200,
        "LapsCount": 1,
        "Description": "200 m",
        "ShortDescription": "200 m",
        "DescriptionEn": "200 Metres",
        "ShortDescriptionEn": "200 M",
    },
    {
        "Id": 70,
        "Sort": 70,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 300,
        "LapsCount": 1,
        "Description": "300 m",
        "ShortDescription": "300 m",
        "DescriptionEn": "300 Metres",
        "ShortDescriptionEn": "300 M",
    },
    {
        "Id": 80,
        "Sort": 80,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 400,
        "LapsCount": 1,
        "Description": "400 m",
        "ShortDescription": "400 m",
        "DescriptionEn": "400 Metres",
        "ShortDescriptionEn": "400 M",
    },
    {
        "Id": 90,
        "Sort": 90,
        "DisciplineType": 1,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.#",
        "TrackLength": 500,
        "LapsCount": 1,
        "Description": "500 m",
        "ShortDescription": "500 m",
        "DescriptionEn": "500 Metres",
        "ShortDescriptionEn": "500 M",
    },
    {
        "Id": 100,
        "Sort": 100,
        "DisciplineType": 1,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.#",
        "TrackLength": 600,
        "LapsCount": 1,
        "Description": "600 m",
        "ShortDescription": "600 m",
        "DescriptionEn": "600 Metres",
        "ShortDescriptionEn": "600 M",
    },
    {
        "Id": 110,
        "Sort": 110,
        "DisciplineType": 1,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.#",
        "TrackLength": 800,
        "LapsCount": 2,
        "Description": "800 m",
        "ShortDescription": "800 m",
        "DescriptionEn": "800 Metres",
        "ShortDescriptionEn": "800 M",
    },
    {
        "Id": 120,
        "Sort": 120,
        "DisciplineType": 1,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.#",
        "TrackLength": 1000,
        "LapsCount": 2,
        "Description": "1000 m",
        "ShortDescription": "1000 m",
        "DescriptionEn": "1000 Metres",
        "ShortDescriptionEn": "1000 M",
    },
    {
        "Id": 130,
        "Sort": 130,
        "DisciplineType": 1,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.#",
        "TrackLength": 1500,
        "LapsCount": 3,
        "Description": "1500 m",
        "ShortDescription": "1500 m",
        "DescriptionEn": "1500 Metres",
        "ShortDescriptionEn": "1500 M",
    },
    {
        "Id": 140,
        "Sort": 140,
        "DisciplineType": 1,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.#",
        "TrackLength": 1609,
        "LapsCount": 3,
        "Description": "1 anglická míle",
        "ShortDescription": "1 míle",
        "DescriptionEn": "One Mile",
        "ShortDescriptionEn": "One Mile",
    },
    {
        "Id": 150,
        "Sort": 150,
        "DisciplineType": 1,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.#",
        "TrackLength": 2000,
        "LapsCount": 5,
        "Description": "2000 m",
        "ShortDescription": "2000 m",
        "DescriptionEn": "2000 Metres",
        "ShortDescriptionEn": "2000 M",
    },
    {
        "Id": 160,
        "Sort": 160,
        "DisciplineType": 1,
        "Mask": "##:##.##",
        "MaskWithoutCamera": "##:##.#",
        "TrackLength": 3000,
        "LapsCount": 7,
        "Description": "3000 m",
        "ShortDescription": "3000 m",
        "DescriptionEn": "3000 Metres",
        "ShortDescriptionEn": "3000 M",
    },
    {
        "Id": 162,
        "Sort": 162,
        "DisciplineType": 1,
        "Mask": "##:##.##",
        "MaskWithoutCamera": "##:##.#",
        "TrackLength": 3218,
        "LapsCount": 8,
        "Description": "2 anglické míle",
        "ShortDescription": "2 míle",
        "DescriptionEn": "2 miles",
        "ShortDescriptionEn": "2 miles",
    },
    {
        "Id": 170,
        "Sort": 180,
        "DisciplineType": 1,
        "Mask": "##:##.##",
        "MaskWithoutCamera": "##:##.#",
        "TrackLength": 5000,
        "LapsCount": 12,
        "Description": "5000 m",
        "ShortDescription": "5000 m",
        "DescriptionEn": "5000 Metres",
        "ShortDescriptionEn": "5000 M",
    },
    {
        "Id": 180,
        "Sort": 190,
        "DisciplineType": 1,
        "Mask": "##:##.##",
        "MaskWithoutCamera": "##:##.#",
        "TrackLength": 10000,
        "LapsCount": 25,
        "Description": "10000 m",
        "ShortDescription": "10000 m",
        "DescriptionEn": "10000 Metres",
        "ShortDescriptionEn": "10000 M",
    },
    {
        "Id": 190,
        "Sort": 200,
        "DisciplineType": 1,
        "Mask": "#:##:##.#",
        "MaskWithoutCamera": "#:##:##.#",
        "TrackLength": 20000,
        "LapsCount": 50,
        "Description": "20000 m",
        "ShortDescription": "20000 m",
        "DescriptionEn": "20000 Metres",
        "ShortDescriptionEn": "20000 M",
    },
    {
        "Id": 200,
        "Sort": 210,
        "DisciplineType": 1,
        "Mask": "#:##:##.#",
        "MaskWithoutCamera": "#:##:##.#",
        "TrackLength": 25000,
        "LapsCount": 62,
        "Description": "25000 m",
        "ShortDescription": "25000 m",
        "DescriptionEn": "25000 Metres",
        "ShortDescriptionEn": "25000 M",
    },
    {
        "Id": 210,
        "Sort": 220,
        "DisciplineType": 1,
        "Mask": "#:##:##.#",
        "MaskWithoutCamera": "#:##:##.#",
        "TrackLength": 30000,
        "LapsCount": 75,
        "Description": "30000 m",
        "ShortDescription": "30000 m",
        "DescriptionEn": "30000 Metres",
        "ShortDescriptionEn": "30000 M",
    },
    {
        "Id": 214,
        "Sort": 224,
        "DisciplineType": 1,
        "Mask": "##:##",
        "MaskWithoutCamera": "##:##",
        "TrackLength": 5000,
        "LapsCount": "",
        "Description": "5 km silnice",
        "ShortDescription": "5 km",
        "DescriptionEn": "5 km road",
        "ShortDescriptionEn": "5 km",
    },
    {
        "Id": 220,
        "Sort": 230,
        "DisciplineType": 1,
        "Mask": "##:##",
        "MaskWithoutCamera": "##:##",
        "TrackLength": 10000,
        "LapsCount": "",
        "Description": "10 km silnice",
        "ShortDescription": "10 km",
        "DescriptionEn": "10 km road",
        "ShortDescriptionEn": "10 km",
    },
    {
        "Id": 230,
        "Sort": 240,
        "DisciplineType": 1,
        "Mask": "##:##",
        "MaskWithoutCamera": "##:##",
        "TrackLength": 15000,
        "LapsCount": "",
        "Description": "15 km silnice",
        "ShortDescription": "15 km",
        "DescriptionEn": "15 km road",
        "ShortDescriptionEn": "15 km",
    },
    {
        "Id": 240,
        "Sort": 250,
        "DisciplineType": 1,
        "Mask": "#:##:##",
        "MaskWithoutCamera": "#:##:##",
        "TrackLength": 20000,
        "LapsCount": "",
        "Description": "20 km silnice",
        "ShortDescription": "20 km",
        "DescriptionEn": "20 km road",
        "ShortDescriptionEn": "20 km",
    },
    {
        "Id": 250,
        "Sort": 260,
        "DisciplineType": 1,
        "Mask": "#:##:##",
        "MaskWithoutCamera": "#:##:##",
        "TrackLength": 25000,
        "LapsCount": "",
        "Description": "25 km silnice",
        "ShortDescription": "25 km",
        "DescriptionEn": "25 km road",
        "ShortDescriptionEn": "25 km",
    },
    {
        "Id": 255,
        "Sort": 270,
        "DisciplineType": 1,
        "Mask": "#:##:##",
        "MaskWithoutCamera": "#:##:##",
        "TrackLength": 30000,
        "LapsCount": "",
        "Description": "30 km silnice",
        "ShortDescription": "30 km",
        "DescriptionEn": "30 km road",
        "ShortDescriptionEn": "30 km",
    },
    {
        "Id": 256,
        "Sort": 273,
        "DisciplineType": 1,
        "Mask": "#:##:##",
        "MaskWithoutCamera": "#:##:##",
        "TrackLength": 50000,
        "LapsCount": "",
        "Description": "50 km silnice",
        "ShortDescription": "50 km",
        "DescriptionEn": "50 km road",
        "ShortDescriptionEn": "50 km",
    },
    {
        "Id": 257,
        "Sort": 277,
        "DisciplineType": 1,
        "Mask": "#:##:##",
        "MaskWithoutCamera": "#:##:##",
        "TrackLength": 100000,
        "LapsCount": "",
        "Description": "100 km silnice",
        "ShortDescription": "100 km",
        "DescriptionEn": "100 km road",
        "ShortDescriptionEn": "100 km",
    },
    {
        "Id": 258,
        "Sort": 258,
        "DisciplineType": 1,
        "Mask": "#:##:##",
        "MaskWithoutCamera": "#:##:##",
        "TrackLength": 100000,
        "LapsCount": "",
        "Description": "silniční štafeta",
        "ShortDescription": "štafeta silnice",
        "DescriptionEn": "Road relay",
        "ShortDescriptionEn": "Road relay",
    },
    {
        "Id": 260,
        "Sort": 290,
        "DisciplineType": 1,
        "Mask": "#:##:##",
        "MaskWithoutCamera": "#:##:##",
        "TrackLength": 42195,
        "LapsCount": "",
        "Description": "maratón",
        "ShortDescription": "maratón",
        "DescriptionEn": "Marathon",
        "ShortDescriptionEn": "Marathon",
    },
    {
        "Id": 270,
        "Sort": 280,
        "DisciplineType": 1,
        "Mask": "#:##:##",
        "MaskWithoutCamera": "#:##:##",
        "TrackLength": 21098,
        "LapsCount": "",
        "Description": "půlmaratón",
        "ShortDescription": "půlmaratón",
        "DescriptionEn": "Half Marathon",
        "ShortDescriptionEn": "Half Marathon",
    },
    {
        "Id": 280,
        "Sort": 295,
        "DisciplineType": 2,
        "Mask": "#####",
        "MaskWithoutCamera": "#####",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "hodinovka běh",
        "ShortDescription": "hodinovka",
        "DescriptionEn": "One Hour",
        "ShortDescriptionEn": "One Hour",
    },
    {
        "Id": 290,
        "Sort": 300,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 50,
        "LapsCount": 1,
        "Description": "50 m překážek [106,7 cm]",
        "ShortDescription": "50m p 106,7",
        "DescriptionEn": "50 Metres Hurdles [106,7 cm]",
        "ShortDescriptionEn": "50 m H 106,7",
    },
    {
        "Id": 291,
        "Sort": 301,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 50,
        "LapsCount": 1,
        "Description": "50 m překážek [99,1 cm]",
        "ShortDescription": "50m p 99,1",
        "DescriptionEn": "50 Metres Hurdles [99,1 cm]",
        "ShortDescriptionEn": "50 m H",
    },
    {
        "Id": 292,
        "Sort": 302,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 50,
        "LapsCount": 1,
        "Description": "50 m překážek [91,4 cm]",
        "ShortDescription": "50m p 91,4",
        "DescriptionEn": "50 Metres Hurdles [91,4 cm]",
        "ShortDescriptionEn": "50 m H",
    },
    {
        "Id": 293,
        "Sort": 303,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 50,
        "LapsCount": 1,
        "Description": "50 m překážek [83,8 cm]",
        "ShortDescription": "50m p 83,8",
        "DescriptionEn": "50 Metres Hurdles [83,8 cm]",
        "ShortDescriptionEn": "50 m H",
    },
    {
        "Id": 294,
        "Sort": 304,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 50,
        "LapsCount": 1,
        "Description": "50 m překážek [76,2cm-7,70m]",
        "ShortDescription": "50m p 76,2-7,7",
        "DescriptionEn": "50 m Hurdles [76,2cm-7,70m]",
        "ShortDescriptionEn": "50m H 76,2-7,7",
    },
    {
        "Id": 295,
        "Sort": 305,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 50,
        "LapsCount": 1,
        "Description": "50 m překážek [76,2cm-8,20m]",
        "ShortDescription": "50m p 76,2-8,2",
        "DescriptionEn": "50 m Hurdles [76,2cm-8,20m]",
        "ShortDescriptionEn": "50m H 76,2-8,2",
    },
    {
        "Id": 296,
        "Sort": 306,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 50,
        "LapsCount": 1,
        "Description": "50 m překážek [76,2cm-8,50m]",
        "ShortDescription": "50m p 76,2-8,5",
        "DescriptionEn": "50 m Hurdles [76,2cm-8,50m]",
        "ShortDescriptionEn": "50m H 76,2-8,5",
    },
    {
        "Id": 298,
        "Sort": 316,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 60,
        "LapsCount": 1,
        "Description": "60 m překážek [76,2cm-8,20m]",
        "ShortDescription": "60m p 76,2-8,2",
        "DescriptionEn": "60 m Hurdles [76,2cm-8,20m]",
        "ShortDescriptionEn": "60m H 76,2-8,2",
    },
    {
        "Id": 299,
        "Sort": 317,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 60,
        "LapsCount": 1,
        "Description": "60 m překážek [76,2cm-8,50m]",
        "ShortDescription": "60m p 76,2-8,5",
        "DescriptionEn": "60 m Hurdles [76,2cm-8,50m]",
        "ShortDescriptionEn": "60m H 76,2-8,5",
    },
    {
        "Id": 300,
        "Sort": 310,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 60,
        "LapsCount": 1,
        "Description": "60 m překážek [106,7 cm]",
        "ShortDescription": "60m p 106,7",
        "DescriptionEn": "60 Metres Hurdles [106,7 cm]",
        "ShortDescriptionEn": "60 m H 106,7",
    },
    {
        "Id": 301,
        "Sort": 311,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 60,
        "LapsCount": 1,
        "Description": "60 m překážek [99,1 cm]",
        "ShortDescription": "60m p 99,1",
        "DescriptionEn": "60 m Hurdles [99,1 cm]",
        "ShortDescriptionEn": "60 m H 99,1",
    },
    {
        "Id": 302,
        "Sort": 312,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 60,
        "LapsCount": 1,
        "Description": "60 m překážek [91,4 cm]",
        "ShortDescription": "60m p 91,4",
        "DescriptionEn": "60 m Hurdles [91,4 cm]",
        "ShortDescriptionEn": "60 m H 91,4",
    },
    {
        "Id": 303,
        "Sort": 313,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 60,
        "LapsCount": 1,
        "Description": "60 m překážek [83,8 cm]",
        "ShortDescription": "60m p 83,8",
        "DescriptionEn": "60 m Hurdles [83,8 cm]",
        "ShortDescriptionEn": "60 m H 83,8",
    },
    {
        "Id": 304,
        "Sort": 315,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 60,
        "LapsCount": 1,
        "Description": "60 m překážek [76,2cm-7,70m]",
        "ShortDescription": "60m p 76,2-7,7",
        "DescriptionEn": "60 m Hurdles [76,2cm-7,70m]",
        "ShortDescriptionEn": "60m H 76,2-7,7",
    },
    {
        "Id": 310,
        "Sort": 330,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 100,
        "LapsCount": 1,
        "Description": "100 m překážek [83,8cm]",
        "ShortDescription": "100m p 83,8",
        "DescriptionEn": "100 m Hurdles [83,8cm]",
        "ShortDescriptionEn": "100 m H 83,8",
    },
    {
        "Id": 311,
        "Sort": 331,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 100,
        "LapsCount": 1,
        "Description": "100 m překážek [76,2cm-8,20m]",
        "ShortDescription": "100m p 76,2-8,2",
        "DescriptionEn": "100 m Hurdles [76,2cm-8,20m]",
        "ShortDescriptionEn": "100m H 76,2-8,2",
    },
    {
        "Id": 312,
        "Sort": 332,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 100,
        "LapsCount": 1,
        "Description": "100 m překážek [76,2cm-8,50m]",
        "ShortDescription": "100m p 76,2-8,5",
        "DescriptionEn": "100 m Hurdles [76,2cm-8,50m]",
        "ShortDescriptionEn": "100m H 76,2-8,5",
    },
    {
        "Id": 320,
        "Sort": 340,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 110,
        "LapsCount": 1,
        "Description": "110 m překážek [106,7 cm]",
        "ShortDescription": "110m p 106,7",
        "DescriptionEn": "110 m Hurdles [106,7 cm]",
        "ShortDescriptionEn": "110 m H 106,7",
    },
    {
        "Id": 321,
        "Sort": 341,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 110,
        "LapsCount": 1,
        "Description": "110 m překážek [99,1 cm]",
        "ShortDescription": "110m p 99,1",
        "DescriptionEn": "110 m Hurdles [99,1 cm]",
        "ShortDescriptionEn": "110 m H 99,1",
    },
    {
        "Id": 322,
        "Sort": 342,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 110,
        "LapsCount": 1,
        "Description": "110 m překážek [91,4 cm]",
        "ShortDescription": "110m p 91,4",
        "DescriptionEn": "110 m Hurdles [91,4 cm]",
        "ShortDescriptionEn": "110 m H 91,4",
    },
    {
        "Id": 330,
        "Sort": 350,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 200,
        "LapsCount": 1,
        "Description": "200 m překážek [76,2 cm]",
        "ShortDescription": "200m p 76,2",
        "DescriptionEn": "200 m Hurdles [76,2 cm]",
        "ShortDescriptionEn": "200 m H 76,2",
    },
    {
        "Id": 340,
        "Sort": 360,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 300,
        "LapsCount": 1,
        "Description": "300 m překážek [91,4 cm]",
        "ShortDescription": "300m p 91,4",
        "DescriptionEn": "300 m Hurdles [91,4 cm]",
        "ShortDescriptionEn": "300 m H 91,4",
    },
    {
        "Id": 341,
        "Sort": 361,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 300,
        "LapsCount": 1,
        "Description": "300 m překážek [83,8 cm]",
        "ShortDescription": "300m p 83,8",
        "DescriptionEn": "300 m Hurdles [83,8 cm]",
        "ShortDescriptionEn": "300 m H 83,8",
    },
    {
        "Id": 342,
        "Sort": 362,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 300,
        "LapsCount": 1,
        "Description": "300 m překážek [76,2 cm]",
        "ShortDescription": "300m p 76,2",
        "DescriptionEn": "300 m Hurdles [76,2 cm]",
        "ShortDescriptionEn": "300 m H 76,2",
    },
    {
        "Id": 350,
        "Sort": 370,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 400,
        "LapsCount": 1,
        "Description": "400 m překážek [91,4 cm]",
        "ShortDescription": "400m p 91,4",
        "DescriptionEn": "400 m Hurdles [91,4 cm]",
        "ShortDescriptionEn": "400 m H 91,4",
    },
    {
        "Id": 351,
        "Sort": 371,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 400,
        "LapsCount": 1,
        "Description": "400 m překážek [83,8 cm]",
        "ShortDescription": "400m p 83,8",
        "DescriptionEn": "400 m Hurdles [83,8 cm]",
        "ShortDescriptionEn": "400 m H 83,8",
    },
    {
        "Id": 352,
        "Sort": 372,
        "DisciplineType": 1,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 400,
        "LapsCount": 1,
        "Description": "400 m překážek [76,2 cm]",
        "ShortDescription": "400m p 76,2",
        "DescriptionEn": "400 m Hurdles [76,2 cm]",
        "ShortDescriptionEn": "400 m H 76,2",
    },
    {
        "Id": 360,
        "Sort": 380,
        "DisciplineType": 1,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.#",
        "TrackLength": 1500,
        "LapsCount": 3,
        "Description": "1500 m překážek [76,2 cm]",
        "ShortDescription": "1500m p 76,2",
        "DescriptionEn": "1500 m Hurdles [76,2 cm]",
        "ShortDescriptionEn": "1500 m H 76,2",
    },
    {
        "Id": 370,
        "Sort": 390,
        "DisciplineType": 1,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.#",
        "TrackLength": 2000,
        "LapsCount": 5,
        "Description": "2000 m překážek [91,4 cm]",
        "ShortDescription": "2000m p 91,4",
        "DescriptionEn": "2000 m Hurdles [91,4 cm]",
        "ShortDescriptionEn": "2000 m H 91,4",
    },
    {
        "Id": 371,
        "Sort": 392,
        "DisciplineType": 1,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.#",
        "TrackLength": 2000,
        "LapsCount": 5,
        "Description": "2000 m překážek [76,2 cm]",
        "ShortDescription": "2000m p 76,2",
        "DescriptionEn": "2000 m Hurdles [76,2 cm]",
        "ShortDescriptionEn": "2000 m H",
    },
    {
        "Id": 372,
        "Sort": 391,
        "DisciplineType": 1,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.#",
        "TrackLength": 2000,
        "LapsCount": 5,
        "Description": "2000 m překážek [83,8 cm]",
        "ShortDescription": "2000m p 83,8",
        "DescriptionEn": "2000 m Hurdles [76,2 cm]",
        "ShortDescriptionEn": "2000 m H",
    },
    {
        "Id": 380,
        "Sort": 400,
        "DisciplineType": 1,
        "Mask": "##:##.##",
        "MaskWithoutCamera": "##:##.#",
        "TrackLength": 3000,
        "LapsCount": 7,
        "Description": "3000 m překážek [91,4 cm]",
        "ShortDescription": "3000m p 91,4",
        "DescriptionEn": "3000 m Metres St. [91,4 cm]",
        "ShortDescriptionEn": "3000 m st. 91,4",
    },
    {
        "Id": 381,
        "Sort": 401,
        "DisciplineType": 1,
        "Mask": "##:##.##",
        "MaskWithoutCamera": "##:##.#",
        "TrackLength": 3000,
        "LapsCount": 7,
        "Description": "3000 m překážek [76,2 cm]",
        "ShortDescription": "3000m p 76,2",
        "DescriptionEn": "3000 m Metres St. [76,2 cm]",
        "ShortDescriptionEn": "3000 m st. 76,2",
    },
    {
        "Id": 510,
        "Sort": 410,
        "DisciplineType": 3,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 240,
        "LapsCount": 1,
        "Description": "4 x 60 m",
        "ShortDescription": "4x60 m",
        "DescriptionEn": "4 x 60 Metres Relay",
        "ShortDescriptionEn": "4x60 m",
    },
    {
        "Id": 511,
        "Sort": 411,
        "DisciplineType": 3,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 240,
        "LapsCount": 1,
        "Description": "4 x 60 m kombinovaná",
        "ShortDescription": "4 x 60 m kombi",
        "DescriptionEn": "4 x 60 Metres Relay combined",
        "ShortDescriptionEn": "4 x 60 m comb.",
    },
    {
        "Id": 520,
        "Sort": 420,
        "DisciplineType": 3,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 400,
        "LapsCount": 1,
        "Description": "4 x 100 m",
        "ShortDescription": "4x100 m",
        "DescriptionEn": "4 x 100 Metres Relay",
        "ShortDescriptionEn": "4x100 m",
    },
    {
        "Id": 521,
        "Sort": 421,
        "DisciplineType": 3,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.#",
        "TrackLength": 400,
        "LapsCount": 1,
        "Description": "4 x 100 m kombinovaná",
        "ShortDescription": "4 x 100 m kombi",
        "DescriptionEn": "4 x 100 Metres Relay combined",
        "ShortDescriptionEn": "4 x 100m comb.",
    },
    {
        "Id": 530,
        "Sort": 430,
        "DisciplineType": 3,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.#",
        "TrackLength": 800,
        "LapsCount": 2,
        "Description": "4 x 200 m",
        "ShortDescription": "4x200 m",
        "DescriptionEn": "4 x 200 Metres Relay",
        "ShortDescriptionEn": "4x200 m",
    },
    {
        "Id": 531,
        "Sort": 431,
        "DisciplineType": 3,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.#",
        "TrackLength": 800,
        "LapsCount": 2,
        "Description": "4 x 200 m kombinovaná",
        "ShortDescription": "4 x 200 m kombi",
        "DescriptionEn": "4 x 200 Metres Relay combined",
        "ShortDescriptionEn": "4 x 200m comb.",
    },
    {
        "Id": 532,
        "Sort": 532,
        "DisciplineType": 3,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.#",
        "TrackLength": 1200,
        "LapsCount": 3,
        "Description": "6 x 200 m",
        "ShortDescription": "6x200m",
        "DescriptionEn": "6 x 200 Metres Relay",
        "ShortDescriptionEn": "6x200m",
    },
    {
        "Id": 534,
        "Sort": 534,
        "DisciplineType": 3,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.##",
        "TrackLength": 1600,
        "LapsCount": 4,
        "Description": "8 x 200 m",
        "ShortDescription": "8x200m",
        "DescriptionEn": "8 x 200 Metres Relay",
        "ShortDescriptionEn": "8x200m",
    },
    {
        "Id": 535,
        "Sort": 435,
        "DisciplineType": 3,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.#",
        "TrackLength": 1200,
        "LapsCount": 4,
        "Description": "4 x 300 m",
        "ShortDescription": "4x300 m",
        "DescriptionEn": "4 x 300 Metres Relay",
        "ShortDescriptionEn": "4x300 m",
    },
    {
        "Id": 536,
        "Sort": 436,
        "DisciplineType": 3,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.#",
        "TrackLength": 1200,
        "LapsCount": 4,
        "Description": "4 x 300 m kombinovaná",
        "ShortDescription": "4 x 300 m kombi",
        "DescriptionEn": "4 x 300 Metres Relay combined",
        "ShortDescriptionEn": "4 x 300m comb.",
    },
    {
        "Id": 540,
        "Sort": 440,
        "DisciplineType": 3,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.#",
        "TrackLength": 1600,
        "LapsCount": 4,
        "Description": "4 x 400 m",
        "ShortDescription": "4x400 m",
        "DescriptionEn": "4 x 400 Metres Relay",
        "ShortDescriptionEn": "4x400 m",
    },
    {
        "Id": 541,
        "Sort": 441,
        "DisciplineType": 3,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.#",
        "TrackLength": 1600,
        "LapsCount": 4,
        "Description": "4 x 400 m kombinovaná",
        "ShortDescription": "4 x 400 m kombi",
        "DescriptionEn": "4 x 400 Metres Relay combined",
        "ShortDescriptionEn": "4 x 400m comb.",
    },
    {
        "Id": 545,
        "Sort": 445,
        "DisciplineType": 3,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.#",
        "TrackLength": 1600,
        "LapsCount": 4,
        "Description": "4 x 400 m mix",
        "ShortDescription": "4x400 m mix",
        "DescriptionEn": "4 x 400 Metres Relay mix",
        "ShortDescriptionEn": "4x400 m mix",
    },
    {
        "Id": 550,
        "Sort": 450,
        "DisciplineType": 3,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.#",
        "TrackLength": 3200,
        "LapsCount": 8,
        "Description": "4 x 800 m",
        "ShortDescription": "4x800 m",
        "DescriptionEn": "4 x 800 Metres Relay",
        "ShortDescriptionEn": "4x800 m",
    },
    {
        "Id": 551,
        "Sort": 451,
        "DisciplineType": 3,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.#",
        "TrackLength": 3200,
        "LapsCount": 8,
        "Description": "4 x 800 m kombinovaná",
        "ShortDescription": "4 x 800 m kombi",
        "DescriptionEn": "4 x 800 Metres Relay combined",
        "ShortDescriptionEn": "4 x 800m comb.",
    },
    {
        "Id": 560,
        "Sort": 460,
        "DisciplineType": 3,
        "Mask": "##:##.##",
        "MaskWithoutCamera": "##:##.#",
        "TrackLength": 6000,
        "LapsCount": 15,
        "Description": "4 x 1500 m",
        "ShortDescription": "4x1500 m",
        "DescriptionEn": "4 x 1500 Metres Relay",
        "ShortDescriptionEn": "4x1500 m",
    },
    {
        "Id": 561,
        "Sort": 461,
        "DisciplineType": 3,
        "Mask": "##:##.##",
        "MaskWithoutCamera": "##:##.#",
        "TrackLength": 6000,
        "LapsCount": 15,
        "Description": "4 x 1500 m kombinovaná",
        "ShortDescription": "4 x 1500m kombi",
        "DescriptionEn": "4 x 1500 Metres Relay combined",
        "ShortDescriptionEn": "4 x 1500m comb.",
    },
    {
        "Id": 570,
        "Sort": 470,
        "DisciplineType": 3,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.#",
        "TrackLength": 900,
        "LapsCount": 2,
        "Description": "3 x 300 m",
        "ShortDescription": "3x300 m",
        "DescriptionEn": "3 x 300 Metres Relay",
        "ShortDescriptionEn": "3x300 m",
    },
    {
        "Id": 580,
        "Sort": 480,
        "DisciplineType": 3,
        "Mask": "##:##.##",
        "MaskWithoutCamera": "##:##.#",
        "TrackLength": 3000,
        "LapsCount": 7,
        "Description": "3 x 1000 m",
        "ShortDescription": "3x1000 m",
        "DescriptionEn": "3 x 1000 Metres Relay",
        "ShortDescriptionEn": "3x1000 m",
    },
    {
        "Id": 590,
        "Sort": 490,
        "DisciplineType": 3,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.#",
        "TrackLength": 1000,
        "LapsCount": 2,
        "Description": "100-200-300-400 m",
        "ShortDescription": "1-2-3-4",
        "DescriptionEn": "100-200-300-400 Metres Relay",
        "ShortDescriptionEn": "1-2-3-4",
    },
    {
        "Id": 600,
        "Sort": 500,
        "DisciplineType": 3,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.#",
        "TrackLength": 1000,
        "LapsCount": 2,
        "Description": "400-300-200-100 m",
        "ShortDescription": "4-3-2-1",
        "DescriptionEn": "400-300-200-100 Metres Relay",
        "ShortDescriptionEn": "4-3-2-1",
    },
    {
        "Id": 610,
        "Sort": 510,
        "DisciplineType": 3,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.#",
        "TrackLength": 1500,
        "LapsCount": 3,
        "Description": "800-400-200-100 m",
        "ShortDescription": "8-4-2-1",
        "DescriptionEn": "800-400-200-100 Metres Relay",
        "ShortDescriptionEn": "8-4-2-1",
    },
    {
        "Id": 620,
        "Sort": 520,
        "DisciplineType": 3,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.#",
        "TrackLength": 1600,
        "LapsCount": 4,
        "Description": "800-400-200-200 m",
        "ShortDescription": "8-4-2-2",
        "DescriptionEn": "800-400-200-200 Metres Relay",
        "ShortDescriptionEn": "8-4-2-2",
    },
    {
        "Id": 630,
        "Sort": 850,
        "DisciplineType": 4,
        "Mask": "####",
        "MaskWithoutCamera": "####",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "sprintérský trojboj",
        "ShortDescription": "sprint. tr",
        "DescriptionEn": "Sprint triathlon",
        "ShortDescriptionEn": "Sprint. tr",
    },
    {
        "Id": 640,
        "Sort": 540,
        "DisciplineType": 3,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.#",
        "TrackLength": 2000,
        "LapsCount": 5,
        "Description": "600-400-200-800 m",
        "ShortDescription": "6-4-2-8",
        "DescriptionEn": "600-400-200-800 Metres Relay",
        "ShortDescriptionEn": "6-4-2-8",
    },
    {
        "Id": 650,
        "Sort": 530,
        "DisciplineType": 3,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.#",
        "TrackLength": 1800,
        "LapsCount": 4,
        "Description": "600-300-100-800 m",
        "ShortDescription": "6-3-1-8",
        "DescriptionEn": "600-300-100-800 Metres Relay",
        "ShortDescriptionEn": "6-3-1-8",
    },
    {
        "Id": 700,
        "Sort": 770,
        "DisciplineType": 4,
        "Mask": "####",
        "MaskWithoutCamera": "####",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "pohár rozhlasu",
        "ShortDescription": "poharR",
        "DescriptionEn": "Radio cup",
        "ShortDescriptionEn": "RadioC",
    },
    {
        "Id": 705,
        "Sort": 775,
        "DisciplineType": 4,
        "Mask": "####",
        "MaskWithoutCamera": "####",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "středoškolský pohár",
        "ShortDescription": "strPohar",
        "DescriptionEn": "School cup",
        "ShortDescriptionEn": "SchoolC",
    },
    {
        "Id": 710,
        "Sort": 780,
        "DisciplineType": 4,
        "Mask": "####",
        "MaskWithoutCamera": "####",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "pětiboj",
        "ShortDescription": "pětiboj",
        "DescriptionEn": "Pentathlon",
        "ShortDescriptionEn": "Pentathlon",
    },
    {
        "Id": 715,
        "Sort": 790,
        "DisciplineType": 4,
        "Mask": "####",
        "MaskWithoutCamera": "####",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "pětiboj hala",
        "ShortDescription": "pětiboj h",
        "DescriptionEn": "Pentathlon h",
        "ShortDescriptionEn": "Pentathlon h",
    },
    {
        "Id": 720,
        "Sort": 800,
        "DisciplineType": 4,
        "Mask": "####",
        "MaskWithoutCamera": "####",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "sedmiboj",
        "ShortDescription": "sedmiboj",
        "DescriptionEn": "Heptathlon",
        "ShortDescriptionEn": "Heptathlon",
    },
    {
        "Id": 725,
        "Sort": 725,
        "DisciplineType": 4,
        "Mask": "####",
        "MaskWithoutCamera": "####",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "sedmiboj IAAF",
        "ShortDescription": "sedmiboj IAAF",
        "DescriptionEn": "Heptathlon IAAF",
        "ShortDescriptionEn": "heptathlon IAAF",
    },
    {
        "Id": 730,
        "Sort": 810,
        "DisciplineType": 4,
        "Mask": "####",
        "MaskWithoutCamera": "####",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "sedmiboj hala",
        "ShortDescription": "sedmiboj h",
        "DescriptionEn": "Heptathlon h",
        "ShortDescriptionEn": "heptathlon h",
    },
    {
        "Id": 740,
        "Sort": 815,
        "DisciplineType": 4,
        "Mask": "",
        "MaskWithoutCamera": "",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "osmiboj",
        "ShortDescription": "osmiboj",
        "DescriptionEn": "Octathlon",
        "ShortDescriptionEn": "Octathlon",
    },
    {
        "Id": 745,
        "Sort": 745,
        "DisciplineType": 4,
        "Mask": "####",
        "MaskWithoutCamera": "####",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "osmiboj IAAF",
        "ShortDescription": "osmiboj IAAF",
        "DescriptionEn": "Octathlon IAAF",
        "ShortDescriptionEn": "Octathlon IAAF",
    },
    {
        "Id": 750,
        "Sort": 820,
        "DisciplineType": 4,
        "Mask": "####",
        "MaskWithoutCamera": "####",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "devítiboj",
        "ShortDescription": "devítiboj",
        "DescriptionEn": "Nonathlon",
        "ShortDescriptionEn": "Nonathlon",
    },
    {
        "Id": 760,
        "Sort": 830,
        "DisciplineType": 4,
        "Mask": "####",
        "MaskWithoutCamera": "####",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "desetiboj",
        "ShortDescription": "desetiboj",
        "DescriptionEn": "Decathlon",
        "ShortDescriptionEn": "Decathlon",
    },
    {
        "Id": 770,
        "Sort": 840,
        "DisciplineType": 4,
        "Mask": "####",
        "MaskWithoutCamera": "####",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "klasický pětiboj",
        "ShortDescription": "pětiboj kl",
        "DescriptionEn": "Classic pentathlon",
        "ShortDescriptionEn": "Cl. pentathlon",
    },
    {
        "Id": 780,
        "Sort": 860,
        "DisciplineType": 4,
        "Mask": "####",
        "MaskWithoutCamera": "####",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "vrhačský trojboj",
        "ShortDescription": "vrh. tr.",
        "DescriptionEn": "Throws triathlon",
        "ShortDescriptionEn": "Thr. tr.",
    },
    {
        "Id": 790,
        "Sort": 870,
        "DisciplineType": 4,
        "Mask": "####",
        "MaskWithoutCamera": "####",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "vrhačský čtyřboj",
        "ShortDescription": "vrh. čtyř",
        "DescriptionEn": "Throwing tetrathlon",
        "ShortDescriptionEn": "Thr. tetrathlon",
    },
    {
        "Id": 800,
        "Sort": 880,
        "DisciplineType": 4,
        "Mask": "####",
        "MaskWithoutCamera": "####",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "vrhačský pětiboj",
        "ShortDescription": "vrh. pětiboj",
        "DescriptionEn": "Throws pentathlon",
        "ShortDescriptionEn": "Thr. pentathlon",
    },
    {
        "Id": 810,
        "Sort": 810,
        "DisciplineType": 4,
        "Mask": "####",
        "MaskWithoutCamera": "####",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "čtyřboj",
        "ShortDescription": "čtyřboj",
        "DescriptionEn": "Tetrathlon",
        "ShortDescriptionEn": "Tetrathlon",
    },
    {
        "Id": 815,
        "Sort": 815,
        "DisciplineType": 4,
        "Mask": "####",
        "MaskWithoutCamera": "####",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "trojboj",
        "ShortDescription": "trojboj",
        "DescriptionEn": "Triathlon",
        "ShortDescriptionEn": "Triathlon",
    },
    {
        "Id": 910,
        "Sort": 730,
        "DisciplineType": 6,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "hod břemenem 10kg",
        "ShortDescription": "břemeno 10kg",
        "DescriptionEn": "Weight throw 10kg",
        "ShortDescriptionEn": "Weight 10kg",
    },
    {
        "Id": 920,
        "Sort": 740,
        "DisciplineType": 6,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "hod břemenem 12kg",
        "ShortDescription": "břemeno 12kg",
        "DescriptionEn": "Weight throw 12kg",
        "ShortDescriptionEn": "Weight 12kg",
    },
    {
        "Id": 930,
        "Sort": 750,
        "DisciplineType": 6,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "hod břemenem 14kg",
        "ShortDescription": "břemeno 14kg",
        "DescriptionEn": "Weight throw 14kg",
        "ShortDescriptionEn": "Weight 14kg",
    },
    {
        "Id": 940,
        "Sort": 760,
        "DisciplineType": 6,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "hod břemenem 16kg",
        "ShortDescription": "břemeno 16kg",
        "DescriptionEn": "Weight throw 16kg",
        "ShortDescriptionEn": "Weight 16kg",
    },
    {
        "Id": 949,
        "Sort": 609,
        "DisciplineType": 6,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "hod diskem 0,75kg",
        "ShortDescription": "disk 0,75kg",
        "DescriptionEn": "Discus Throw 0,75kg",
        "ShortDescriptionEn": "Discus 0,75kg",
    },
    {
        "Id": 950,
        "Sort": 610,
        "DisciplineType": 6,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "hod diskem 1kg",
        "ShortDescription": "disk 1kg",
        "DescriptionEn": "Discus Throw 1kg",
        "ShortDescriptionEn": "Discus 1kg",
    },
    {
        "Id": 960,
        "Sort": 620,
        "DisciplineType": 6,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "hod diskem 1,5kg",
        "ShortDescription": "disk 1,5kg",
        "DescriptionEn": "Discus Throw 1,5kg",
        "ShortDescriptionEn": "Discus 1,5kg",
    },
    {
        "Id": 970,
        "Sort": 630,
        "DisciplineType": 6,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "hod diskem 1,75kg",
        "ShortDescription": "disk 1,75kg",
        "DescriptionEn": "Discus Throw 1,75kg",
        "ShortDescriptionEn": "Discus 1,75kg",
    },
    {
        "Id": 980,
        "Sort": 640,
        "DisciplineType": 6,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "hod diskem 2kg",
        "ShortDescription": "disk 2kg",
        "DescriptionEn": "Discus Throw 2kg",
        "ShortDescriptionEn": "Discus 2kg",
    },
    {
        "Id": 989,
        "Sort": 649,
        "DisciplineType": 6,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "hod kladivem 2kg",
        "ShortDescription": "kladivo 2kg",
        "DescriptionEn": "Hammer Throw 2kg",
        "ShortDescriptionEn": "Hammer 2kg",
    },
    {
        "Id": 990,
        "Sort": 650,
        "DisciplineType": 6,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "hod kladivem 3kg",
        "ShortDescription": "kladivo 3kg",
        "DescriptionEn": "Hammer Throw 3kg",
        "ShortDescriptionEn": "Hammer 3kg",
    },
    {
        "Id": 1000,
        "Sort": 660,
        "DisciplineType": 6,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "hod kladivem 4kg",
        "ShortDescription": "kladivo 4kg",
        "DescriptionEn": "Hammer Throw 4kg",
        "ShortDescriptionEn": "Hammer 4kg",
    },
    {
        "Id": 1010,
        "Sort": 670,
        "DisciplineType": 6,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "hod kladivem 5kg",
        "ShortDescription": "kladivo 5kg",
        "DescriptionEn": "Hammer Throw 5kg",
        "ShortDescriptionEn": "Hammer 5kg",
    },
    {
        "Id": 1020,
        "Sort": 680,
        "DisciplineType": 6,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "hod kladivem 6kg",
        "ShortDescription": "kladivo 6kg",
        "DescriptionEn": "Hammer Throw 6kg",
        "ShortDescriptionEn": "Hammer 6kg",
    },
    {
        "Id": 1030,
        "Sort": -1,
        "DisciplineType": 6,
        "Mask": "",
        "MaskWithoutCamera": "",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "hod kladivem 6,25kg",
        "ShortDescription": "kladivo 6,25kg",
        "DescriptionEn": "Hammer Throw 6,25kg",
        "ShortDescriptionEn": "Hammer 6,25kg",
    },
    {
        "Id": 1040,
        "Sort": 690,
        "DisciplineType": 6,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "hod kladivem 7,26kg",
        "ShortDescription": "kladivo 7,26kg",
        "DescriptionEn": "Hammer Throw 7,26kg",
        "ShortDescriptionEn": "Hammer 7,26kg",
    },
    {
        "Id": 1048,
        "Sort": 698,
        "DisciplineType": 6,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "hod oštěpem 400g",
        "ShortDescription": "oštěp 400g",
        "DescriptionEn": "Javelin 400g",
        "ShortDescriptionEn": "Javelin 400g",
    },
    {
        "Id": 1049,
        "Sort": 699,
        "DisciplineType": 6,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "hod oštěpem 500g",
        "ShortDescription": "oštěp 500g",
        "DescriptionEn": "Javelin Throw 500g",
        "ShortDescriptionEn": "Javelin 500g",
    },
    {
        "Id": 1050,
        "Sort": 700,
        "DisciplineType": 6,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "hod oštěpem 600g",
        "ShortDescription": "oštěp 600g",
        "DescriptionEn": "Javelin Throw 600g",
        "ShortDescriptionEn": "Javelin 600g",
    },
    {
        "Id": 1060,
        "Sort": 711,
        "DisciplineType": 6,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "hod oštěpem 700g starý typ",
        "ShortDescription": "oštěp 700g s",
        "DescriptionEn": "Javelin Throw 700g old type",
        "ShortDescriptionEn": "Javelin 700g s",
    },
    {
        "Id": 1061,
        "Sort": 710,
        "DisciplineType": 6,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "hod oštěpem 700g nový typ",
        "ShortDescription": "oštěp 700g n",
        "DescriptionEn": "Javelin Throw 700g new type",
        "ShortDescriptionEn": "Javelin 700g n",
    },
    {
        "Id": 1070,
        "Sort": 720,
        "DisciplineType": 6,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "hod oštěpem 800g",
        "ShortDescription": "oštěp 800g",
        "DescriptionEn": "Javelin Throw 800g",
        "ShortDescriptionEn": "Javelin 800g",
    },
    {
        "Id": 1080,
        "Sort": 770,
        "DisciplineType": 6,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "hod kriketovým míčkem",
        "ShortDescription": "kriket",
        "DescriptionEn": "Cricket throw",
        "ShortDescriptionEn": "Cricket",
    },
    {
        "Id": 1085,
        "Sort": 559,
        "DisciplineType": 6,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "vrh koulí 2kg",
        "ShortDescription": "koule 2kg",
        "DescriptionEn": "Shot Put 2kg",
        "ShortDescriptionEn": "Shot Put 2kg",
    },
    {
        "Id": 1090,
        "Sort": 560,
        "DisciplineType": 6,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "vrh koulí 3kg",
        "ShortDescription": "koule 3kg",
        "DescriptionEn": "Shot Put 3kg",
        "ShortDescriptionEn": "Shot Put 3kg",
    },
    {
        "Id": 1100,
        "Sort": 570,
        "DisciplineType": 6,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "vrh koulí 4kg",
        "ShortDescription": "koule 4kg",
        "DescriptionEn": "Shot Put 4kg",
        "ShortDescriptionEn": "Shot Put 4kg",
    },
    {
        "Id": 1110,
        "Sort": 580,
        "DisciplineType": 6,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "vrh koulí 5kg",
        "ShortDescription": "koule 5kg",
        "DescriptionEn": "Shot Put 5kg",
        "ShortDescriptionEn": "Shot Put 5kg",
    },
    {
        "Id": 1120,
        "Sort": 590,
        "DisciplineType": 6,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "vrh koulí 6kg",
        "ShortDescription": "koule 6kg",
        "DescriptionEn": "Shot Put 6kg",
        "ShortDescriptionEn": "Shot Put 6kg",
    },
    {
        "Id": 1130,
        "Sort": -1,
        "DisciplineType": 6,
        "Mask": "",
        "MaskWithoutCamera": "",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "vrh koulí 6,25kg",
        "ShortDescription": "koule 6,25kg",
        "DescriptionEn": "Shot Put 6,25kg",
        "ShortDescriptionEn": "Shot Put 6,25kg",
    },
    {
        "Id": 1140,
        "Sort": 600,
        "DisciplineType": 6,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "vrh koulí 7,26kg",
        "ShortDescription": "koule 7,26kg",
        "DescriptionEn": "Shot Put 7,26kg",
        "ShortDescriptionEn": "Shot Put 7,26kg",
    },
    {
        "Id": 1310,
        "Sort": 550,
        "DisciplineType": 2,
        "Mask": "#.##",
        "MaskWithoutCamera": "#.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "skok daleký",
        "ShortDescription": "dálka",
        "DescriptionEn": "Long Jump",
        "ShortDescriptionEn": "Long Jump",
    },
    {
        "Id": 1311,
        "Sort": 551,
        "DisciplineType": 2,
        "Mask": "#.##",
        "MaskWithoutCamera": "#.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "skok z místa",
        "ShortDescription": "skok z místa",
        "DescriptionEn": "skok z místa",
        "ShortDescriptionEn": "skok z místa",
    },
    {
        "Id": 1320,
        "Sort": 555,
        "DisciplineType": 2,
        "Mask": "##.##",
        "MaskWithoutCamera": "##.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "trojskok",
        "ShortDescription": "trojskok",
        "DescriptionEn": "Triple Jump",
        "ShortDescriptionEn": "Triple Jump",
    },
    {
        "Id": 1330,
        "Sort": 540,
        "DisciplineType": 5,
        "Mask": "#.##",
        "MaskWithoutCamera": "#.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "skok o tyči",
        "ShortDescription": "tyč",
        "DescriptionEn": "Pole Vault",
        "ShortDescriptionEn": "Pole Vault",
    },
    {
        "Id": 1340,
        "Sort": 530,
        "DisciplineType": 5,
        "Mask": "#.##",
        "MaskWithoutCamera": "#.##",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "skok vysoký",
        "ShortDescription": "výška",
        "DescriptionEn": "High Jump",
        "ShortDescriptionEn": "High Jump",
    },
    {
        "Id": 1402,
        "Sort": 870,
        "DisciplineType": 1,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.#",
        "TrackLength": 500,
        "LapsCount": "",
        "Description": "chůze dráha 500 m",
        "ShortDescription": "chůze 500m",
        "DescriptionEn": "500m walk",
        "ShortDescriptionEn": "500m walk",
    },
    {
        "Id": 1403,
        "Sort": 872,
        "DisciplineType": 1,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.#",
        "TrackLength": 800,
        "LapsCount": 2,
        "Description": "chůze dráha 800 m",
        "ShortDescription": "chůze 800m",
        "DescriptionEn": "800m walk",
        "ShortDescriptionEn": "800m walk",
    },
    {
        "Id": 1404,
        "Sort": 875,
        "DisciplineType": 1,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.#",
        "TrackLength": 1000,
        "LapsCount": "",
        "Description": "chůze dráha 1000 m",
        "ShortDescription": "chůze 1000m",
        "DescriptionEn": "1000m walk",
        "ShortDescriptionEn": "1000m walk",
    },
    {
        "Id": 1405,
        "Sort": 877,
        "DisciplineType": 1,
        "Mask": "#:##.##",
        "MaskWithoutCamera": "#:##.#",
        "TrackLength": 1500,
        "LapsCount": "",
        "Description": "chůze dráha 1500 m",
        "ShortDescription": "chůze 1500m",
        "DescriptionEn": "1500m walk",
        "ShortDescriptionEn": "1500m walk",
    },
    {
        "Id": 1410,
        "Sort": 880,
        "DisciplineType": 1,
        "Mask": "##:##.##",
        "MaskWithoutCamera": "##:##.#",
        "TrackLength": 2000,
        "LapsCount": "",
        "Description": "chůze dráha 2000 m",
        "ShortDescription": "chůze 2000m",
        "DescriptionEn": "Race walk 2000m",
        "ShortDescriptionEn": "RW 2000m",
    },
    {
        "Id": 1420,
        "Sort": 890,
        "DisciplineType": 1,
        "Mask": "##:##.##",
        "MaskWithoutCamera": "##:##.#",
        "TrackLength": 3000,
        "LapsCount": "",
        "Description": "chůze dráha 3000 m",
        "ShortDescription": "chůze 3000m",
        "DescriptionEn": "Race walk 3000 m",
        "ShortDescriptionEn": "RW 3000m",
    },
    {
        "Id": 1430,
        "Sort": 900,
        "DisciplineType": 1,
        "Mask": "##:##.##",
        "MaskWithoutCamera": "##:##.#",
        "TrackLength": 5000,
        "LapsCount": "",
        "Description": "chůze dráha 5000 m",
        "ShortDescription": "chůze 5000m",
        "DescriptionEn": "Race Walk 5000 m",
        "ShortDescriptionEn": "RW 5000m",
    },
    {
        "Id": 1440,
        "Sort": 910,
        "DisciplineType": 1,
        "Mask": "##:##.##",
        "MaskWithoutCamera": "##:##.#",
        "TrackLength": 10000,
        "LapsCount": "",
        "Description": "chůze dráha 10000 m",
        "ShortDescription": "chůze 10000m",
        "DescriptionEn": "Race Walk 10000 m",
        "ShortDescriptionEn": "RW 10000m",
    },
    {
        "Id": 1450,
        "Sort": 920,
        "DisciplineType": 1,
        "Mask": "#:##:##.#",
        "MaskWithoutCamera": "#:##:##.#",
        "TrackLength": 20000,
        "LapsCount": "",
        "Description": "chůze dráha 20000 m",
        "ShortDescription": "chůze 20000m",
        "DescriptionEn": "Race Walk 20000 m",
        "ShortDescriptionEn": "RW 20000m",
    },
    {
        "Id": 1460,
        "Sort": 930,
        "DisciplineType": 1,
        "Mask": "#:##:##.#",
        "MaskWithoutCamera": "#:##:##.#",
        "TrackLength": 30000,
        "LapsCount": "",
        "Description": "chůze dráha 30000 m",
        "ShortDescription": "chůze 30000m",
        "DescriptionEn": "Race Walk 30000 m",
        "ShortDescriptionEn": "RW 30000m",
    },
    {
        "Id": 1465,
        "Sort": 935,
        "DisciplineType": 1,
        "Mask": "#:##:##.#",
        "MaskWithoutCamera": "#:##:##.#",
        "TrackLength": 35000,
        "LapsCount": "",
        "Description": "chůze dráha 35000 m",
        "ShortDescription": "chůze 35000m",
        "DescriptionEn": "Race Walk 35000 m",
        "ShortDescriptionEn": "RW 35000m",
    },
    {
        "Id": 1470,
        "Sort": 940,
        "DisciplineType": 1,
        "Mask": "#:##:##.#",
        "MaskWithoutCamera": "#:##:##.#",
        "TrackLength": 50000,
        "LapsCount": "",
        "Description": "chůze dráha 50000 m",
        "ShortDescription": "chůze 50000m",
        "DescriptionEn": "Race Walk 50000 m",
        "ShortDescriptionEn": "RW 50000m",
    },
    {
        "Id": 1480,
        "Sort": 960,
        "DisciplineType": 2,
        "Mask": "#####",
        "MaskWithoutCamera": "#####",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "dvouhodinovka chůze",
        "ShortDescription": "chůze 2hod.",
        "DescriptionEn": "Race walk 2hrs",
        "ShortDescriptionEn": "RW 2hrs",
    },
    {
        "Id": 1490,
        "Sort": 950,
        "DisciplineType": 2,
        "Mask": "#####",
        "MaskWithoutCamera": "#####",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "hodinovka chůze",
        "ShortDescription": "chůze 1hod.",
        "DescriptionEn": "Race walk 1hr",
        "ShortDescriptionEn": "RW 1hr",
    },
    {
        "Id": 1491,
        "Sort": 960,
        "DisciplineType": 1,
        "Mask": "##:##",
        "MaskWithoutCamera": "##:##",
        "TrackLength": 1000,
        "LapsCount": "",
        "Description": "1 km chůze",
        "ShortDescription": "1km chůze",
        "DescriptionEn": "1 Km Race Walk",
        "ShortDescriptionEn": "1 Km RW",
    },
    {
        "Id": 1492,
        "Sort": 961,
        "DisciplineType": 1,
        "Mask": "##:##",
        "MaskWithoutCamera": "##:##",
        "TrackLength": 2000,
        "LapsCount": "",
        "Description": "2 km chůze",
        "ShortDescription": "2km chůze",
        "DescriptionEn": "2 Km Race Walk",
        "ShortDescriptionEn": "2 Km RW",
    },
    {
        "Id": 1500,
        "Sort": 970,
        "DisciplineType": 1,
        "Mask": "##:##",
        "MaskWithoutCamera": "##:##",
        "TrackLength": 3000,
        "LapsCount": "",
        "Description": "3 km chůze",
        "ShortDescription": "3km chůze",
        "DescriptionEn": "3 Km Race Walk",
        "ShortDescriptionEn": "3 Km RW",
    },
    {
        "Id": 1510,
        "Sort": 980,
        "DisciplineType": 1,
        "Mask": "##:##",
        "MaskWithoutCamera": "##:##",
        "TrackLength": 5000,
        "LapsCount": "",
        "Description": "5 km chůze",
        "ShortDescription": "5km chůze",
        "DescriptionEn": "5 Km Race Walk",
        "ShortDescriptionEn": "5 Km RW",
    },
    {
        "Id": 1520,
        "Sort": 990,
        "DisciplineType": 1,
        "Mask": "##:##",
        "MaskWithoutCamera": "##:##",
        "TrackLength": 10000,
        "LapsCount": "",
        "Description": "10 km chůze",
        "ShortDescription": "10km chůze",
        "DescriptionEn": "10 Km Race Walk",
        "ShortDescriptionEn": "10 Km RW",
    },
    {
        "Id": 1530,
        "Sort": 1000,
        "DisciplineType": 1,
        "Mask": "#:##:##",
        "MaskWithoutCamera": "#:##:##",
        "TrackLength": 20000,
        "LapsCount": "",
        "Description": "20 km chůze",
        "ShortDescription": "20km chůze",
        "DescriptionEn": "20 Km Race Walk",
        "ShortDescriptionEn": "20 Km RW",
    },
    {
        "Id": 1540,
        "Sort": 1010,
        "DisciplineType": 1,
        "Mask": "#:##:##",
        "MaskWithoutCamera": "#:##:##",
        "TrackLength": 30000,
        "LapsCount": "",
        "Description": "30 km chůze",
        "ShortDescription": "30km chůze",
        "DescriptionEn": "30 Km Race Walk",
        "ShortDescriptionEn": "30 Km RW",
    },
    {
        "Id": 1545,
        "Sort": 1015,
        "DisciplineType": 1,
        "Mask": "#:##:##",
        "MaskWithoutCamera": "#:##:##",
        "TrackLength": 35000,
        "LapsCount": "",
        "Description": "35 km chůze",
        "ShortDescription": "35km chůze",
        "DescriptionEn": "35 Km Race Walk",
        "ShortDescriptionEn": "35 Km RW",
    },
    {
        "Id": 1550,
        "Sort": 1020,
        "DisciplineType": 1,
        "Mask": "#:##:##",
        "MaskWithoutCamera": "#:##:##",
        "TrackLength": 50000,
        "LapsCount": "",
        "Description": "50 km chůze",
        "ShortDescription": "50km chůze",
        "DescriptionEn": "50 Km Race Walk ",
        "ShortDescriptionEn": "50 Km RW",
    },
    {
        "Id": 1600,
        "Sort": 1025,
        "DisciplineType": 3,
        "Mask": "#:##:##.#",
        "MaskWithoutCamera": "#:##:##.#",
        "TrackLength": 42195,
        "LapsCount": "",
        "Description": "Maratónská chodecká štaf. mix",
        "ShortDescription": "Chodecká štaf.m",
        "DescriptionEn": "Marathon walking relay mix",
        "ShortDescriptionEn": "walking relay m",
    },
    {
        "Id": 8000,
        "Sort": 8000,
        "DisciplineType": 1,
        "Mask": "#:##:##",
        "MaskWithoutCamera": "#:##:##",
        "TrackLength": 4000,
        "LapsCount": "",
        "Description": "Přespolní běh",
        "ShortDescription": "Přespolní běh",
        "DescriptionEn": "Cross",
        "ShortDescriptionEn": "Cross",
    },
    {
        "Id": 8001,
        "Sort": 8001,
        "DisciplineType": 1,
        "Mask": "#:##:##",
        "MaskWithoutCamera": "#:##:##",
        "TrackLength": 9000,
        "LapsCount": "",
        "Description": "Přespolní běh-vytrvalci",
        "ShortDescription": "PBěh vytrvalci",
        "DescriptionEn": "CrossV",
        "ShortDescriptionEn": "CrossV",
    },
    {
        "Id": 8002,
        "Sort": 8002,
        "DisciplineType": 1,
        "Mask": "#:##:##",
        "MaskWithoutCamera": "#:##:##",
        "TrackLength": 8000,
        "LapsCount": "",
        "Description": "Přespolní běh mílaři",
        "ShortDescription": "PBěh mílaři",
        "DescriptionEn": "CrossM",
        "ShortDescriptionEn": "CrossM",
    },
    {
        "Id": 8003,
        "Sort": 8003,
        "DisciplineType": 1,
        "Mask": "#:##:##",
        "MaskWithoutCamera": "#:##:##",
        "TrackLength": 10000,
        "LapsCount": "",
        "Description": " Běh do vrchu",
        "ShortDescription": "Vrchy",
        "DescriptionEn": "Mountain Running",
        "ShortDescriptionEn": "MRun",
    },
    {
        "Id": 8004,
        "Sort": 8004,
        "DisciplineType": 1,
        "Mask": "#:##:##",
        "MaskWithoutCamera": "#:##:#",
        "TrackLength": 10000,
        "LapsCount": "",
        "Description": "Běh do vrchu",
        "ShortDescription": "Vrch",
        "DescriptionEn": "Mountain Running",
        "ShortDescriptionEn": "Mountain",
    },
    {
        "Id": 8005,
        "Sort": 8002,
        "DisciplineType": 3,
        "Mask": "#:##:##",
        "MaskWithoutCamera": "#:##:##",
        "TrackLength": 4000,
        "LapsCount": "",
        "Description": "Přespolní běh - štafeta",
        "ShortDescription": "Běh štafeta",
        "DescriptionEn": "Cross Relay",
        "ShortDescriptionEn": "CrossR",
    },
    {
        "Id": 8010,
        "Sort": 8010,
        "DisciplineType": 1,
        "Mask": "#:##:##",
        "MaskWithoutCamera": "#:##:#",
        "TrackLength": 10000,
        "LapsCount": "",
        "Description": "Dlouhý horský běh",
        "ShortDescription": "Dl. horský běh",
        "DescriptionEn": "Long mountain run",
        "ShortDescriptionEn": "Mountain long",
    },
    {
        "Id": 9000,
        "Sort": 9998,
        "DisciplineType": 3,
        "Mask": "",
        "MaskWithoutCamera": "",
        "TrackLength": "",
        "LapsCount": "",
        "Description": "Celkový bodový stav",
        "ShortDescription": "Body",
        "DescriptionEn": "Points",
        "ShortDescriptionEn": "Points",
    },
]
