"""create new db

Revision ID: 282b09fb739c
Revises:
Create Date: 2026-01-13 10:22:30.158537

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "282b09fb739c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "athlete",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("bank_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("birth_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("street", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("zip", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("ean", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("club_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("profile_image_id", sa.Uuid(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_athlete_id"), "athlete", ["id"], unique=False)
    op.create_table(
        "athlete_guardian",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("athlete_id", sa.Uuid(), nullable=False),
        sa.Column("guardian_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("athlete_id", "guardian_id"),
    )
    op.create_table(
        "athlete_meet_event",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("athlete_id", sa.Uuid(), nullable=False),
        sa.Column("meet_event_id", sa.Uuid(), nullable=False),
        sa.Column("result", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("wind", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("pb_sb", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("points", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("bib", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("athlete_id", "meet_event_id"),
    )
    op.create_table(
        "athlete_registration_meet_event",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("athlete_id", sa.Uuid(), nullable=False),
        sa.Column("meet_event_id", sa.Uuid(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("athlete_id", "meet_event_id"),
    )
    op.create_table(
        "athlete_sign_up_form",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("athlete_id", sa.Uuid(), nullable=False),
        sa.Column("sign_up_form_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("athlete_id", "sign_up_form_id"),
    )
    op.create_table(
        "category",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sex", sa.Integer(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "short_description", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("description_en", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "short_description_en", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("age", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "club",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_club_id"), "club", ["id"], unique=False)
    op.create_table(
        "discipline",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("traditional", sa.Integer(), nullable=True),
        sa.Column("discipline_type_id", sa.Integer(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "short_description", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("description_en", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "short_description_en", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "discipline_type",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sort", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("name_en", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description_en", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "file",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("mime_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_file_id"), "file", ["id"], unique=False)
    op.create_table(
        "group",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("training_time_id", sa.Uuid(), nullable=False),
        sa.Column("school_year_id", sa.Uuid(), nullable=False),
        sa.Column("system", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_group_id"), "group", ["id"], unique=False)
    op.create_table(
        "group_athlete",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("athlete_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("group_id", "athlete_id"),
    )
    op.create_table(
        "group_trainer",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("trainer_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("group_id", "trainer_id"),
    )
    op.create_table(
        "guardian",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("bank_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_guardian_id"), "guardian", ["id"], unique=False)
    op.create_table(
        "helper",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("bank_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("lats_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("street", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("zip", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("qualification", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("preferrence", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_helper_id"), "helper", ["id"], unique=False)
    op.create_table(
        "item",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("image_id", sa.Uuid(), nullable=True),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("item_type_id", sa.Uuid(), nullable=False),
        sa.Column("athlete_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_item_id"), "item", ["id"], unique=False)
    op.create_table(
        "item_type",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_item_type_id"), "item_type", ["id"], unique=False)
    op.create_table(
        "meet",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("external_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("registration_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("registration_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("registration_limit", sa.Integer(), nullable=True),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("organizer", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_meet_id"), "meet", ["id"], unique=False)
    op.create_table(
        "meet_event",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("meet_id", sa.Uuid(), nullable=False),
        sa.Column("discipline_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("phase", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("count", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_meet_event_id"), "meet_event", ["id"], unique=False)
    op.create_table(
        "meet_trainer",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("meet_id", sa.Uuid(), nullable=False),
        sa.Column("trainer_id", sa.Uuid(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("presence", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("meet_id", "trainer_id"),
    )
    op.create_index(
        op.f("ix_meet_trainer_meet_id"), "meet_trainer", ["meet_id"], unique=False
    )
    op.create_table(
        "payment",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("from_id", sa.Uuid(), nullable=True),
        sa.Column("to_id", sa.Uuid(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "points",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("athlete_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("type", "source_id", "athlete_id"),
    )
    op.create_table(
        "remote_config",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("urgent_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("show_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("show_to", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "minimum_app_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_remote_config_id"), "remote_config", ["id"], unique=False)
    op.create_table(
        "request",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_request_id"), "request", ["id"], unique=False)
    op.create_table(
        "request_file",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("request_id", "file_id"),
    )
    op.create_table(
        "response",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("person_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_response_id"), "response", ["id"], unique=False)
    op.create_table(
        "school_year",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_school_year_id"), "school_year", ["id"], unique=False)
    op.create_table(
        "sign_up_form",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("birth_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("street", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("zip", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "guardian_first_name1", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "guardian_last_name1", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "guardian_first_name2", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "guardian_last_name2", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "guardian_phone1", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "guardian_email1", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("guardian_phone2", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("guardian_email2", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("school_year_id", sa.Uuid(), nullable=False),
        sa.Column("times_per_week", sa.Integer(), nullable=False),
        sa.Column("days_in_week", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sign_up_form_id"), "sign_up_form", ["id"], unique=False)
    op.create_table(
        "sign_up_form_group",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sign_up_form_id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("sign_up_form_id", "group_id"),
    )
    op.create_table(
        "trainer",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("athlete_id", sa.Uuid(), nullable=False),
        sa.Column("bank_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("qualification", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("salary_per_hour", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trainer_id"), "trainer", ["id"], unique=False)
    op.create_table(
        "training",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_training_id"), "training", ["id"], unique=False)
    op.create_table(
        "training_athlete",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("training_id", sa.Uuid(), nullable=False),
        sa.Column("athlete_id", sa.Uuid(), nullable=False),
        sa.Column("presence", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("training_id", "athlete_id"),
    )
    op.create_table(
        "training_time",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("day", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("summer_time", sa.Time(), nullable=False),
        sa.Column("winter_time", sa.Time(), nullable=False),
        sa.Column("duration_summer", sa.Integer(), nullable=False),
        sa.Column("duration_winter", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_training_time_id"), "training_time", ["id"], unique=False)
    op.create_table(
        "training_trainer",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("training_id", sa.Uuid(), nullable=False),
        sa.Column("trainer_id", sa.Uuid(), nullable=False),
        sa.Column("presence", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("training_id", "trainer_id"),
    )
    op.create_table(
        "web_post",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cover_image_id", sa.Uuid(), nullable=True),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("trainer_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_web_post_id"), "web_post", ["id"], unique=False)
    # Ensure timestamp columns are timezone-aware, non-nullable and have defaults
    tables_with_timestamps = [
        "athlete",
        "athlete_guardian",
        "athlete_meet_event",
        "athlete_registration_meet_event",
        "athlete_sign_up_form",
        "category",
        "club",
        "discipline",
        "discipline_type",
        "file",
        "group",
        "group_athlete",
        "group_trainer",
        "guardian",
        "helper",
        "item",
        "item_type",
        "meet",
        "meet_trainer",
        "meet_event",
        "payment",
        "points",
        "remote_config",
        "request",
        "request_file",
        "response",
        "school_year",
        "sign_up_form",
        "sign_up_form_group",
        "trainer",
        "training",
        "training_athlete",
        "training_time",
        "training_trainer",
        "web_post",
    ]

    for _table in tables_with_timestamps:
        try:
            op.alter_column(
                _table,
                "created_at",
                existing_type=sa.DateTime(timezone=True),
                nullable=False,
                server_default=sa.func.now(),
            )
        except Exception:
            # best-effort: skip if column doesn't exist or alteration fails
            pass
        try:
            op.alter_column(
                _table,
                "updated_at",
                existing_type=sa.DateTime(timezone=True),
                nullable=False,
                server_default=sa.func.now(),
            )
        except Exception:
            pass

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_web_post_id"), table_name="web_post")
    op.drop_table("web_post")
    op.drop_table("training_trainer")
    op.drop_index(op.f("ix_training_time_id"), table_name="training_time")
    op.drop_table("training_time")
    op.drop_table("training_athlete")
    op.drop_index(op.f("ix_training_id"), table_name="training")
    op.drop_table("training")
    op.drop_index(op.f("ix_trainer_id"), table_name="trainer")
    op.drop_table("trainer")
    op.drop_table("sign_up_form_group")
    op.drop_index(op.f("ix_sign_up_form_id"), table_name="sign_up_form")
    op.drop_table("sign_up_form")
    op.drop_index(op.f("ix_school_year_id"), table_name="school_year")
    op.drop_table("school_year")
    op.drop_index(op.f("ix_response_id"), table_name="response")
    op.drop_table("response")
    op.drop_table("request_file")
    op.drop_index(op.f("ix_request_id"), table_name="request")
    op.drop_table("request")
    op.drop_index(op.f("ix_remote_config_id"), table_name="remote_config")
    op.drop_table("remote_config")
    op.drop_table("points")
    op.drop_table("payment")
    op.drop_index(op.f("ix_meet_event_id"), table_name="meet_event")
    op.drop_table("meet_event")
    op.drop_index(op.f("ix_meet_id"), table_name="meet")
    op.drop_table("meet")
    op.drop_index(op.f("ix_item_type_id"), table_name="item_type")
    op.drop_table("item_type")
    op.drop_index(op.f("ix_item_id"), table_name="item")
    op.drop_table("item")
    op.drop_index(op.f("ix_helper_id"), table_name="helper")
    op.drop_table("helper")
    op.drop_index(op.f("ix_guardian_id"), table_name="guardian")
    op.drop_table("guardian")
    op.drop_table("group_trainer")
    op.drop_table("group_athlete")
    op.drop_index(op.f("ix_group_id"), table_name="group")
    op.drop_table("group")
    op.drop_index(op.f("ix_file_id"), table_name="file")
    op.drop_table("file")
    op.drop_table("discipline_type")
    op.drop_table("discipline")
    op.drop_index(op.f("ix_club_id"), table_name="club")
    op.drop_table("club")
    op.drop_table("category")
    op.drop_table("athlete_sign_up_form")
    op.drop_table("athlete_registration_meet_event")
    op.drop_table("athlete_meet_event")
    op.drop_table("athlete_guardian")
    op.drop_index(op.f("ix_athlete_id"), table_name="athlete")
    op.drop_table("athlete")
    # ### end Alembic commands ###
